version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017
    expose:
    - '27017'
  twitter_api:
    image: alexburlacu/rtp-server:faf18x
    ports:
      - 4000:4000
    expose:
      - '4000'
  rtp:
    build:
      context: .
    ports:
      - 4444:4444
    expose:
      - '4444'
    depends_on:
      - mongodb
      - twitter_api